AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  File Gateway Service
  Simple, secure way for users to upload and download files without exposing S3 bucket publicly.

Resources:
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cr4-aprudencio-file-gateway-storage-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FileGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref FileStorageBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        UploadFile:
          Type: Api
          Properties:
            Path: /files
            Method: post
        DownloadFile:
          Type: Api
          Properties:
            Path: /files/{key}
            Method: get

Outputs:
  FileGatewayApi:
    Description: "API Gateway endpoint URL for Prod stage for File Gateway function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/files/"
  FileStorageBucketName:
    Description: "S3 Bucket Name"
    Value: !Ref FileStorageBucket
